### PR TITLE
Add typing

### PR DESCRIPTION
**Pull request by dstansby**

### CODE REVIEW

**Comment by Cadair** [comment]
Given we haven't really had a discussion about this in core yet, and we might end up moving this into core depending on how things develop, perhaps we should hold off on this until the coord meeting?

**Comment by dstansby** [comment]
The typing doesn't affect the code that's run at all, so unless anyone has code readability objections I think we might as well merge this? I am a new convert to typing in general, and I think it especially helps annotate what is going on in the attribute walker functions here.

**Comment by nabobalis** [comment]
> I would like to come up with a type hints policy for all sponsored packages before we start using them in a significant way in any of them.

We should/will type all function inputs and output as a start. 

I have been trying to type when I work on any packages that are not sunpy. Though I have not been that successful.

**Comment by dstansby** [comment]
I don't *think* there's any infrastructure issues here (typing and enforcing typing can be entirely optional and done in a piecemeal way, but I agree that

> Not to mention that it add serious congnative overhead for contributors if different packages have different conventions

is a good reason to put this on hold. I will leave this in draft state as an example of what typing something in the sunpy ecosystem looks like though.

**Comment by dstansby** [comment]
Closing this until if/when we decide to use `mypy` across all SunPy packages.

**Pull request closed without merging**
