### PR TITLE
Support path string interpolation

### LINKED ISSUE #23: SOAR client does not correctly handle string interpolation in `Fido.fetch`
When using the `path=...` keyword argument in `Fido.fetch`, string interpolation can be used to direct certain files to certain directories. However, when used with the SOAR client, this throws an exception. This is demonstrated with the following code example:

```python
import sunpy_soar
from sunpy_soar.attrs import Product
from sunpy.net import Fido, attrs as a
result = Fido.search(a.Time("2021-02-12 16:0", "2021-02-13 02:00") & a.Level(2) & a.Instrument('EUI') & Product('EUI-FSI174-IMAGE'))
files = Fido.fetch(result, path='{instrument}')
```

throws the following exception

```python traceback
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Input In [16], in <cell line: 1>()
----> 1 files = Fido.fetch(result[0][:1], path='data/{instrument}')

File ~/anaconda/envs/pyhc-summer-school/lib/python3.9/site-packages/sunpy/net/fido_factory.py:430, in UnifiedDownloaderFactory.fetch(self, path, max_conn, progress, overwrite, downloader, *query_results, **kwargs)
    427     raise ValueError(f"Query result has an unrecognized type: {type(query_result)} "
    428                      "Allowed types are QueryResponseRow, QueryResponseTable or UnifiedResponse.")
    429 for block in responses:
--> 430     result = block.client.fetch(block, path=path,
    431                                 downloader=downloader,
    432                                 wait=False, **kwargs)
    433     if result not in (NotImplemented, None):
    434         reslist.append(result)

File ~/anaconda/envs/pyhc-summer-school/lib/python3.9/site-packages/sunpy_soar/client.py:118, in SOARClient.fetch(self, query_results, path, downloader, **kwargs)
    116 for row in query_results:
    117     url = base_url + row['Data item ID']
--> 118     filepath = str(path).format(file=row['Filename'])
    119     log.debug(f'Queing URL: {url}')
    120     downloader.enqueue_file(url, filename=filepath)

KeyError: 'instrument'
```

### PR DESCRIPTION
**Pull request by wtbarnes**
Fixes #23

### CODE REVIEW

**Comment by wtbarnes** [comment]
These test failures are not related to this PR and are tracked by #26

**Review by dstansby — CHANGES_REQUESTED** [review]
Should probably add a quick test, even if it's just a smoke test?

**Comment by wtbarnes** [comment]
How do these tests handle downloaded files? Do they just download to the default sunpy directory?

**Comment by dstansby** [comment]
Yep

**Comment by dstansby** [comment]
Other tests should be fixed now if you want to rebase

**Pull request merged**
